name: fan-in-fan-out-security
 
on: workflow_dispatch
 
jobs:
  build:
   runs-on: ubuntu-latest
   strategy:
     matrix:
      os: [windows,mac,os]
   steps:
     - run: echo "..."
  
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
     - run: echo "..."
  
  checks:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
     - run: echo "..."
  
  security-scan-windows:
   runs-on: ubuntu-latest
   needs: [lint,checks]
   strategy:
     matrix:
      nodeVer: [4,6,8]
   steps:
     - run: echo "..."
  
  quality-check:
   runs-on: ubuntu-latest
   needs: [security-scan-windows]
   steps:
     - run: echo "..."
  
  security-scan-mac:
   runs-on: ubuntu-latest
   needs: [lint,checks]
   strategy:
     matrix:
      nodeVer: [4,6,8]
   steps:
     - run: echo "..." 
  
  security-scan-os:
   runs-on: ubuntu-latest
   needs: [lint,checks]
   strategy:
     matrix:
      nodeVer: [4,6,8]
   steps:
     - run: echo "..."
  
  staging:
   runs-on: ubuntu-latest
   needs: [quality-check,security-scan-mac,security-scan-os]
   steps:
     - run: echo "..."
  
  uat-test-A:
   runs-on: ubuntu-latest
   needs: [staging]
   steps:
     - run: echo "..." 
  
  uat-test-B:
   runs-on: ubuntu-latest
   needs: [staging]
   steps:
     - run: echo "..."  
  
  uat-test-C:
   runs-on: ubuntu-latest
   needs: [staging]
   steps:
     - run: echo "..."  
  
  deploy:
   runs-on: ubuntu-latest
   needs: [uat-test-A,uat-test-B,uat-test-C]
   steps:
     - run: echo "..."
