name: fan-in-fan-out
 
on: workflow_dispatch
 
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - run: echo "..."
  
  test-A:
   runs-on: ubuntu-latest
   needs: [build]
   steps:
     - run: echo "..."
  
  test-B:
   runs-on: ubuntu-latest
   needs: [build]
   steps:
     - run: echo "..." 
  
  test-C:
   runs-on: ubuntu-latest
   needs: [build]
   steps:
     - run: echo "..."
  
  integration-test:
   runs-on: ubuntu-latest
   needs: [test-A,test-B,test-C]
   steps:
     - run: echo "..."
  
  staging:
   runs-on: ubuntu-latest
   needs: [integration-test]
   steps:
     - run: echo "..."
  
  deploy:
   runs-on: ubuntu-latest
   needs: [staging]
   steps:
     - run: echo "..."
