name: matrix-build-test
 
on: workflow_dispatch
 
jobs:
  build:
   runs-on: ubuntu-latest
   strategy:
    matrix:
      os: [window,linux,mac]
   steps:
     - run: echo "..."
  
  unit-test:
   runs-on: ubuntu-latest
   strategy:
    matrix:
      node-version: [4,6,8]
   needs: [build]
   steps:
     - run: echo "..."
  
  integration-test:
   runs-on: ubuntu-latest
   needs: [unit-test]
   steps:
     - run: echo "..."
  
  deploy:
   runs-on: ubuntu-latest
   needs: [integration-test]
   steps:
     - run: echo "..."

