name: monorepo
 
on: workflow_dispatch
 
jobs:
  backend-build:
   runs-on: ubuntu-latest
   steps:
     - run: echo "..."
  
  frontend-build:
   runs-on: ubuntu-latest
   steps:
     - run: echo "..."
  
  backend-lint:
   runs-on: ubuntu-latest
   needs: [backend-build]
   steps:
     - run: echo "..."
  
  frontend-lint:
   runs-on: ubuntu-latest
   needs: [frontend-build]
   steps:
     - run: echo "..."
  
  backend-test-A:
   runs-on: ubuntu-latest
   needs: [backend-lint]
   steps:
     - run: echo "..."
  
  backend-test-B:
   runs-on: ubuntu-latest
   needs: [backend-lint]
   steps:
     - run: echo "..."
  
  backend-test-C:
   runs-on: ubuntu-latest
   needs: [backend-lint]
   steps:
     - run: echo "..."
  
  frontend-test-A:
   runs-on: ubuntu-latest
   needs: [frontend-lint]
   steps:
     - run: echo "..."
  
  frontend-test-B:
   runs-on: ubuntu-latest
   needs: [frontend-lint]
   steps:
     - run: echo "..."
  
  e2e-test:
   runs-on: ubuntu-latest
   needs: [backend-test-A, backend-test-B, backend-test-C, frontend-test-A, frontend-test-B]
   steps:
     - run: echo "..."
  
  release-candidate:
   runs-on: ubuntu-latest
   needs: [e2e-test]
   steps:
     - run: echo "..."
  
  staging:
   runs-on: ubuntu-latest
   needs: [release-candidate]
   steps:
     - run: echo "..."
  
  deploy:
   runs-on: ubuntu-latest
   needs: [staging]
   steps:
     - run: echo "..."
