name: sequential
 
on: workflow_dispatch
 
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - run: echo "..."
  
  unit-test:
   runs-on: ubuntu-latest
   needs: [build]
   steps:
     - run: echo "..."
  
  integration-test:
   runs-on: ubuntu-latest
   needs: [unit-test]
   steps:
     - run: echo "..."
  
  deploy:
   runs-on: ubuntu-latest
   needs: [integration-test]
   steps:
     - run: echo "..."
